### PR TITLE
Fixing #760 and #761

### LINKED ISSUE #760: Issues in listing APIs isung combined modifiers
**Description:**

- **Command:**  `apictl list apis --environment dev --query provider:admin --insecure`
- **Response :** 

Screenshot from 2021-07-01 21-13-22

- **Command** : `apictl list apis --environment dev --query provider:admin name:PizzaShackAPI --insecure`
- **Response :**  No APIs are returned. 

But the PizzaShackAPI is available matching this query.

- **Command** : `apictl list apis --environment dev --query version:1.0.0  status:PUBLISHED --insecure`
- **Response :**  No APIs are returned. 

But the PizzaShackAPI is available matching this query.

This behavior is reproducible with API products too.

Stack trace in carbon logs:

```
[2021-07-01 21:21:22,589] ERROR - CarbonContextCreatorValve Could not handle request: /api/am/publisher/v1/apis
java.lang.NullPointerException: null
	at org.wso2.carbon.tomcat.ext.internal.Utils.getAppNameFromRequest(Utils.java:104) ~[org.wso2.carbon.tomcat.ext_4.6.0.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.initCarbonContext(CarbonContextCreatorValve.java:80) ~[org.wso2.carbon.tomcat.ext_4.6.0.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:56) [org.wso2.carbon.tomcat.ext_4.6.0.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:124) [org.wso2.carbon.tomcat.ext_4.6.0.jar:?]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1707) [tomcat_9.0.31.wso2v1.jar:?]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat_9.0.31.wso2v1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_251]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_251]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat_9.0.31.wso2v1.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]
```

### Affected versions

- APICTL 3.2.2 tool

### Steps to reproduce

- Create an environment and and Create an API in it.

### LINKED ISSUE #761: Errors when demoting an API from Publish to Created
### Description

When demoting an API from Publish stage to Created the following error is encountered.

**Command:** `apictl change-status api -a Demote to Created -n PizzaShackAPI -v 1.0.0 -e dev -k`

**Response:**

Error while changing API Status:  400  
 {"code":400,"message":"Bad Request","description":"Action 'Demote' is not allowed. Allowed actions are [Block, Deploy as a Prototype, Demote to Created, Deprecate, Publish]","moreInfo":"","error":[]}

**Command:** `apictl change-status api -a Demote%20to%20Created -n PizzaShackAPI -v 1.0.0 -e dev -k`

**Response:** PizzaShackAPI API state changed successfully!

From API Controller can't we Encode the request and send it to APIM instead of asking a user to encode the parameters ?

### Affected Product Version:

APICTL 3.2.2

### PR DESCRIPTION
**Pull request by Chamindu36**
## Purpose
Fixes #760
Fixes #761

### CODE REVIEW

File: import-export-cli/cmd/apis.go [hunk 1]
```diff
@@ -80,7 +80,7 @@ var apisCmd = &cobra.Command{
 		//Since other flags does not use args[], query flag will own this
 		if len(args) != 0 && listApisCmdQuery != "" {
 			for _, argument := range args {
-				listApisCmdQuery +=  " " + argument
+				listApisCmdQuery +=  "&" + argument
```
Comment (wasuradananjith) [inline import-export-cli/cmd/apis.go:83]: Shall we use the constant [1] here?

[1] https://github.com/wso2/product-apim-tooling/blob/3.2.x/import-export-cli/utils/constants.go#L124

**Review by wasuradananjith — APPROVED** [review]

File: import-export-cli/cmd/apis.go (hunk 1 above)
Comment (Chamindu36) [reply import-export-cli/cmd/apis.go]: fixed with b736f4e7253bd8f35a7841654afe80b3a4acba3c

**Review by wasuradananjith — APPROVED** [review]

**Review by uvindra — APPROVED** [review]
