### PR TITLE
Fix for #428

### LINKED ISSUE #428: APIs created with Dev first Approach are not visible in Devportal
**Description:**
APIs created with Dev first Approach using API Controller are not visible in Devportal even though APIs are in the published state.

**Publisher View**
Screenshot from 2020-07-30 13-31-43

**DevPortal Views**
Screenshot from 2020-07-30 13-32-31
 
As in screen shots, Published APIs imported with API controller in dev first approach not visible in Dev portal.

**Suggested Labels:**
Type/bug 

**Affected Product Version:**
3.2.0

**Steps to reproduce:**
1. Initialize a project with API definition using controller.
2. Import that API project using Controller.
3. Change life cycle state to "Published"
4. Check dev Portal.

### PR DESCRIPTION
**Pull request by Chamindu36**
## Purpose
Fixes #428

### CODE REVIEW

File: import-export-cli/cmd/root.go [hunk 1]
```diff
@@ -159,6 +160,23 @@ func createConfigFiles() {
...
 			utils.HandleErrorAndExit("Error creating default api spec file", err)
 		}
+	} else {
+		data, err := ioutil.ReadFile(utils.DefaultAPISpecFilePath)
+		if err != nil {
+			utils.HandleErrorAndExit("Error creating default api spec file", err)
+		}
+		defaultApiFile := make(map[string]interface{})
+		if err := yaml.Unmarshal(data, &defaultApiFile); err != nil {
+			utils.HandleErrorAndExit("Error reading controller-config", err)
```
Comment (malinthaprasan) [inline import-export-cli/cmd/root.go:170]: defalt api yaml?

Comment (Chamindu36) [reply import-export-cli/cmd/root.go]: The file we read here is `default_api.yaml`
